### ISSUE TITLE
Asset Hierarchy - Parent Child is not mapping correctly in SiteWise 

### ISSUE THREAD

**Issue by navilwayne** [aws-quickstart/quickstart-aws-industrial-machine-connectivity#15]
Hi 

@nsstensoriot: We have two Edge Nodes in Ignition Edge like below paths (Path 1 and  2). While using IMC kit (Option 2) it is creating one path correctly whereas another path is not creating hierarchy correctly in Sitewise (unexpected random behaviour). We tried to put a log in Asset model convertor lambda, but not able to find the exact issue. We also have noticed the in Dynamo DB -  table : AssetModel the _assetModelHierarchies_ column is sometimes empty. Please let us know the exact configuration we have to update?

1. Path 1 
XX>
 Hous> 
     AP >
        Robot

2. Path 2: 
XX>
 NJ>
      Phar>
        Robot

ScreenShot : 
![SiteWise18092020](https://user-images.githubusercontent.com/11074957/93597515-cd400b00-f9d8-11ea-9f58-30bbf0b46961.JPG)

![IgnitionEdge18092020](https://user-images.githubusercontent.com/11074957/93597671-109a7980-f9d9-11ea-8a7f-7a11a3b42a91.JPG)

**Comment by TensorIoT-Shahan** [comment]
Hi @navilwayne, based on the previous issue brought up, I assume that the IMC Kit launches properly with the default configuration - but would just like to confirm that's the case. 

Separately, for the case above, a few questions: 

1. The asset creation/hierarchy association process takes quite some time. Is it possible that the process was simply not finished yet? 
2. Is the asset "Pong1991..." represented as a UDT (is it an instantiation of RoboMotor?) For the relationships to be created properly in the IMC Kit, the assets need to be represented as a UDT.

**Comment by navilwayne** [comment]
HI @TensorIoT-Shahan  

Lambda processing is taking 05-08 minutes & config - timeout was set 03 minutes. We increased the timeout limit & working fine.

Thanks
