### ISSUE TITLE
iginitionFileDriver  fails when AtomicTag defined under "Folder" tagType

### ISSUE THREAD

**Issue by mary-element** [aws-quickstart/quickstart-aws-industrial-machine-connectivity#44]
Got this error when using iginitionFileDriver to process ignition export file.
`
KeyError: 'tags' Traceback (most recent call last):   File "/var/task/assetModelConverter.py", line 185, in handler     assetModelClass.processEvent(event)   File "/var/task/assetModelConverter.py", line 167, in processEvent     driver.processEvent(birthEvent)   File "/var/task/drivers/ignitionFileDriver.py", line 333, in processEvent     self.processAssetTree(assetGroup)   File "/var/task/drivers/ignitionFileDriver.py", line 303, in processAssetTree     parentPath=nodePath,   File "/var/task/drivers/ignitionFileDriver.py", line 303, in processAssetTree     parentPath=nodePath,   File "/var/task/drivers/ignitionFileDriver.py", line 298, in processAssetTree     for childValue in nodeValue['tags']:
`

The export file contains AtomicTags defined under "Folder" tagType, which means asset without asset model. Here is the file.
[test-tags.json.zip](https://github.com/aws-quickstart/quickstart-aws-industrial-machine-connectivity/files/6104710/test-tags.json.zip)

Iginition File Driver seems does not treat those tags as an "asset"
https://github.com/aws-quickstart/quickstart-aws-industrial-machine-connectivity/blob/769e667944e8603695a917326c75fb333f538899/functions/source/AssetModelConverter/drivers/ignitionFileDriver.py#L210
I am not sure if user should remove those tags before using the iginitionFileDriver?

**Comment by leovac** [comment]
@mary-element  how did you solve this issue?
